### ISSUE TITLE
Can't use rst2pdf right out after install

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#219]
```
1. rst2pdf won't work with Python2.6 out of box. python setup.py install fails.
2. I installed it using python2.5.
Event this fails.
$ /usr/bin/rst2pdf 1.rst -o 1.pdf
Traceback (most recent call last):
  File "/usr/bin/rst2pdf", line 8, in <module>
    load_entry_point('rst2pdf==0.12.1', 'console_scripts', 'rst2pdf')()
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 277, in
load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 2180, in
load_entry_point
    return ep.load()
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 1913, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File
"/usr/lib/python2.5/site-packages/rst2pdf-0.12.1-py2.5.egg/rst2pdf/createpdf.py"
,
line 76, in <module>
    from flowables import * # our own reportlab flowables
  File
"/usr/lib/python2.5/site-packages/rst2pdf-0.12.1-py2.5.egg/rst2pdf/flowables.py"
,
line 22, in <module>
    from reportlab.platypus.flowables import _listWrapOn, _FUZZ, NullDraw
ImportError: cannot import name NullDraw

```

Original issue reported on code.google.com by `orsenthil@gmail.com` on 15 Oct 2009 at 8:36
