### ISSUE TITLE
Error with reportlab2.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#474]
```
Traceback (most recent call last):
  File "/usr/local/bin/rst2pdf", line 9, in <module>
    load_entry_point('rst2pdf==0.92', 'console_scripts', 'rst2pdf')()
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf-0.92-py2.7.egg/rst2pdf/createpdf.py", line 1445, in main
    section_header_depth=int(options.section_header_depth),
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf-0.92-py2.7.egg/rst2pdf/createpdf.py", line 183, in __init__
    self.loadStyles(stylesheets)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf-0.92-py2.7.egg/rst2pdf/createpdf.py", line 276, in loadStyles
    def_dpi=self.def_dpi)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf-0.92-py2.7.egg/rst2pdf/styles.py", line 527, in __init__
    reportlab.platypus.tables.CellStyle1.fontname=self['base'].fontName
AttributeError: 'module' object has no attribute 'CellStyle1'


Please answer the following questions, they are *very* important:

* Version of rst2pdf?
0.92
* Version of reportlab?
2.6
* Are you using wordaxe, and if true, what version?
Nope
* Are you using rst2pdf with Sphinx, and if true, what version?
No
Please provide any additional information below.

It worked with reportlab2.5, but fails with reportlab2.6

```

Original issue reported on code.google.com by `moril...@gmail.com` on 4 Oct 2012 at 10:24
