### ISSUE TITLE
0.90 doesn't work with Sphinx 1.1.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#438]
```
What steps will reproduce the problem?

    $ make pdf
    sphinx-build -b pdf -d _build/doctrees   . _build/pdf
    Making output directory...
    Running Sphinx v1.1.2

    Extension error:
    Could not import extension rst2pdf.pdfbuilder (exception: cannot import name get_language_avaiblable)
    make: *** [pdf] Error 1

I fixed the obvious typo at line 52 of pdfbuilder.py, then ran into a second 
problem:

    $ make pdf
    sphinx-build -b pdf -d _build/doctrees   . _build/pdf
    Running Sphinx v1.1.2
    loading pickled environment... done
    building [pdf]: targets for 8 source files that are out of date
    updating environment: 0 added, 0 changed, 0 removed
    looking for now-outdated files... none found
    processing foo... index foo-install [snip]
    resolving references...
    done
    writing foo... [ERROR] pdfbuilder.py:126 global name 'lang' is not defined
    Traceback (most recent call last):
      File "/Users/georger/src/kits/output/site-packages/rst2pdf-0.90-py2.7.egg/rst2pdf/pdfbuilder.py", line 123, in write
        docwriter.write(doctree, destination)
      File "/Users/georger/src/kits/output/site-packages/docutils-0.9-py2.7.egg/docutils/writers/__init__.py", line 77, in write
        self.translate()
      File "/Users/georger/src/kits/output/site-packages/rst2pdf-0.90-py2.7.egg/rst2pdf/pdfbuilder.py", line 522, in translate
        self.docutils_languages = {lang: langmod}
    NameError: global name 'lang' is not defined
    FAILED
    build succeeded.

Note: I'm using a docutils snapshot from 2011-12-01.

Please answer the following questions, they are *very* important:

* Version of rst2pdf?
0.90

* Version of reportlab?
2.5

* Are you using wordaxe, and if true, what version?
No

* Are you using rst2pdf with Sphinx, and if true, what version?
1.1.2

Please provide any additional information below.

```

Original issue reported on code.google.com by `geor...@cozi.com` on 5 Mar 2012 at 8:17
