### ISSUE TITLE
 pdfbuilder.py:140 'listiterator' object has no attribute '__next__'

### ISSUE THREAD

**Issue by DomsRoberts** [rst2pdf/rst2pdf#604]
When I try to run the rst2pdf process with a version of Python2.7.12 I get this error  
pdfbuilder.py:140 'listiterator' object has no attribute '__next__'

It is because of the usage of __next__ in rson.py
I thought that it must be an issues between Python 3.x and Python 2.7, so I changed from __next__ to next.
That stopped the error from occurring however it then failed to load any of the styles and I get exceptions where the key 'base' is not found and Critical Errors when loading any of the styles.
Which version of Python does this package actually work with?
Is there anything I need to do to get it to work with Python 2.7.12?
