### ISSUE TITLE
AttributeError: 'BuildEnvironment' object has no attribute 'indexentries'

### ISSUE THREAD

**Issue by aweisi** [rst2pdf/rst2pdf#1014]
build with sphinx version > 4.0.0 fails

[ERROR] pdfbuilder.py:159 Failed to build doc
Traceback (most recent call last):
  File "wpy64-3902\python-3.9.0.amd64\lib\site-packages\rst2pdf\pdfbuilder.py", line 145, in write
    doctree = self.assemble_doctree(
  File "wpy64-3902\python-3.9.0.amd64\lib\site-packages\rst2pdf\pdfbuilder.py", line 232, in assemble_doctree
    t = copy(self.env.**indexentries**)
AttributeError: 'BuildEnvironment' object has no attribute 'indexentries'
FAILED

older version of sphinx throw warning about that: e.g.: sphinx version 3.5.1:
wpy64-3902\python-3.9.0.amd64\lib\site-packages\rst2pdf\pdfbuilder.py:232: RemovedInSphinx40Warning: env.indexentries() is deprecated. Please use IndexDomain instead.
  t = copy(self.env.indexentries)

version: rst2pdf==0.98

pip install sphinx rst2pdf
build pdf docs

**Comment by lornajane** [comment]
Thanks for the bug report. rst2pdf current depends on an old version of sphinx, there's an effort in #984 to track the update work on this (but I don't think anyone has started it yet). Check the requirements file for the expected Sphinx version (from memory I think it's 1.8.x)

**Comment by idryzhov** [comment]
By the way, everything works fine with the latest Sphinx when Index is disabled using `pdf_use_index = False` option.
Can be helpful if you don't really need an Index.

**Comment by lornajane** [comment]
Thank you so much for dropping in with this information, it's a big help!

**Comment by lornajane** [comment]
See also: #980

**Comment by akrabat** [comment]
This should be fixed when #1020 is merged.

**Comment by lornajane** [comment]
Tested with sphinx 4.3.2 and still getting this error. The workaround to not use the index does help though!

**Comment by lornajane** [comment]
Spoke too soon. Updating to latest  `master` does indeed fix this issue. Sorry for the notification noise
