### ISSUE TITLE
Module Index doesn't work with sphinx 1.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#318]
```
Using the latest pull of the Sphinx repository along with the latest
revision of rst2pdf results in:

Traceback (most recent call last):
  File
"/Library/Python/2.6/site-packages/rst2pdf-0.16.dev_r2164-py2.6.egg/rst2pdf/pdfb
uilder.py",
line 112, in write
    appendices=opts.get('pdf_appendices', self.config.pdf_appendices) or [])
  File
"/Library/Python/2.6/site-packages/rst2pdf-0.16.dev_r2164-py2.6.egg/rst2pdf/pdfb
uilder.py",
line 203, in assemble_doctree
    if self.config.pdf_use_modindex and self.env.modules:
AttributeError: BuildEnvironment instance has no attribute 'modules'

If I add "pdf_appendices=''" to the conf.py file, the error is still returned
```

Original issue reported on code.google.com by `hobu....@gmail.com` on 17 May 2010 at 4:19
