### PR TITLE
Build document index also with Sphinx >= 1.4

### LINKED ISSUE #566: sphinx+rst2pdf fails with automodule directive
I am trying to build API documention of one of my projects using sphinx+rst2pdf. Since updating to sphinx-1.4.1 I obtained errors upon building the pdf documention. 

I tried to narrow the problem down to a minimal example with the following documentation code.

```
test documentation
===================

test

API-documentation
=================

.. automodule:: rst2pdf
```

and sphinx _conf.py_ file

```
# -*- coding: utf-8 -*-

# Add any Sphinx extension module names here, as strings.
extensions = [
    'sphinx.ext.autodoc',
    'rst2pdf.pdfbuilder']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'test'
copyright = u'2016, authors'

# The short X.Y version.
version = '1'
# The full version, including alpha/beta/rc tags.
release = version

# -- Options for PDF output --------------------------------------------------
pdf_documents = [
    ('index',
     u'test',
     u'test',
     u'DK'),
]
```

I also attach the files:
[doc.zip](https://github.com/rst2pdf/rst2pdf/files/228079/doc.zip)

When I try to build this with sphinx-1.4.1 and rst2pdf master (commit af7cabb) I obtain the following:

```
sphinx-build -b pdf doc/source/ build/sphinx/
Running Sphinx v1.4.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [pdf]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                      
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing test... index [ERROR] pdfbuilder.py:130 too many values to unpack
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/pdfbuilder.py", line 122, in write
    appendices=opts.get('pdf_appendices', self.config.pdf_appendices) or [])
  File "/usr/lib64/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/pdfbuilder.py", line 209, in assemble_doctree
    index_nodes=genindex_nodes(genindex)
  File "/usr/lib64/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/pdfbuilder.py", line 385, in genindex_nodes
    for entryname, (links, subitems) in entries:
ValueError: too many values to unpack
FAILED
build succeeded.
```

while with sphinx-1.2.2 it generates the pdf output as expected:

```
sphinx-build -b pdf doc/source/ build/sphinx/
Making output directory...
Running Sphinx v1.2.2
loading pickled environment... not yet created
building [pdf]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                            
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing test... index  py-modindex

resolving references...
done
writing test... done
build succeeded.
```

html output is generated successfully with both versions. When removing the _automodule_ line the pdf out is also generated using sphinx-1.4.1

### PR DESCRIPTION
**Pull request by KonstantinShemyak**
Sphinx changed internal representation of `BuildEnvironment.indexentries` in
version 1.4 (commit [e6a5a3a92e938fcd75866b4227db9e0524d58f7c](https://github.com/sphinx-doc/sphinx/commit/e6a5a3a92e938fcd75866b4227db9e0524d58f7c)) by adding one
more value to the list. This causes `pdfbuilder` to fail whenever PDF index is
generated. 

Pdfbuilder is updated accordingly to work with both pre-1.4 and later Sphinx versions.

### CODE REVIEW

**Comment by oz123** [comment]
@KonstantinShemyak fair enough, before I can merege, can link to a simple sphinx project that got broken by this?

**Comment by dkriegner** [comment]
@oz123 The mentioned issue #566 has a simple project which is affected by this bug. I suffer from this bug in building the documentation of [xrayutilities](https://github.com/dkriegner/xrayutilities)

**Comment by KonstantinShemyak** [comment]
@oz123 Here is the minimal project (the one from @dkriegner, further reduced), which builds with `sphinx-1.3.6`, but fails with `sphinx-1.4`:

## conf.py:

```python
extensions = [
    'sphinx.ext.autodoc',
    'rst2pdf.pdfbuilder']

master_doc = '566'

pdf_documents = [
    ('566',
     u'output-filename',
     u'Output Title',
     u'Author'),
]
```
## 566.rst:

```
API-documentation
=================

.. automodule:: rst2pdf
```

## Results:

### Sphinx-1.3.6:

```
(sphinx-1.3.6) rst2pdf@$ sphinx-build -b pdf issue-566/ output
Running Sphinx v1.3.6
loading pickled environment... failed: 'module' object has no attribute 'Symbol'
building [mo]: targets for 0 po files that are out of date
building [pdf]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] 566                                                                       
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing output-filename... 566  py-modindex

resolving references...
done
writing output-filename... done
build succeeded.
```

### Sphinx-1.4:

```
(sphinx-1.4) rst2pdf@$ sphinx-build -b pdf issue-566/ output/
Running Sphinx v1.4
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [pdf]: targets for 1 source files that are out of date
updating environment: [config changed] 1 added, 0 changed, 0 removed
reading sources... [100%] 566                                                                       
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing output-filename... 566 [ERROR] pdfbuilder.py:130 too many values to unpack
Traceback (most recent call last):
  File "/data/KS/src/rst2pdf/sphinx-1.4/local/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/pdfbuilder.py", line 122, in write
    appendices=opts.get('pdf_appendices', self.config.pdf_appendices) or [])
  File "/data/KS/src/rst2pdf/sphinx-1.4/local/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/pdfbuilder.py", line 209, in assemble_doctree
    index_nodes=genindex_nodes(genindex)
  File "/data/KS/src/rst2pdf/sphinx-1.4/local/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/pdfbuilder.py", line 385, in genindex_nodes
    for entryname, (links, subitems) in entries:
ValueError: too many values to unpack
FAILED
build succeeded.
```

At the moment Sphinx builds fail in master (ef8183f) because of #591. I think Sphinx builds must be fixed first, so I'm not yet suggesting to merge this and not rebasing on master.

**Comment by davidcarroll** [comment]
I am having the `ValueError: too many values to unpack` error as well but when I build HTML docs. Luckily, my production build-server is running an earlier version of sphinx and works.

**Comment by netrounds-joakim** [comment]
This should be merged @oz123 is there some reason for this? @KonstantinShemyak gave an example of a project that fails.

**Comment by netrounds-joakim** [comment]
Another issue that is tied to this, but was closed because the ticket creator was happy with just fixing it in his local version: https://github.com/rst2pdf/rst2pdf/issues/568

**Comment by doctorlard** [comment]
This alteration works with both Sphinx 1.3.x and >= 1.4
Is there any reason this hasn't been merged?

**Comment by oz123** [comment]
@doctorlard the only reason, is that I am currently the sole active maintainer. I simply lack the time to review the PRs.

**Comment by KonstantinShemyak** [comment]
I rebased the (tiny) fix onto the master.

**Comment by pfalcon** [comment]
+1, Please merge ;-)

**Comment by akrabat** [comment]
Fix cherry-picked into #619.
