### ISSUE TITLE
Headers and footers do not work with ReportLab 2.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#100]
```
I get the following error when using headers or footers with ReportLab 2.3:

AttributeError: FancyDocTemplate instance has no attribute 'frame'


```

Original issue reported on code.google.com by `ch.zwerschke@gmail.com` on 12 Feb 2009 at 6:31
