### PR TITLE
Support Sphinx 4

### LINKED ISSUE #749: Test with Sphinx 2.0
Beta for Sphinx 2.0 was just announced, with "breaking API changes" so it will probably break pdfbuilder.

### LINKED ISSUE #980: RemovedInSphinx40Warning: env.indexentries() is deprecated. Please use IndexDomain instead.
I get the the following warning when using rst2pdf with sphinx
>RemovedInSphinx40Warning: env.indexentries() is deprecated. Please use IndexDomain instead.

### the entire output
```text
c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\rst2pdf\pdfbuilder.py:232: RemovedInSphinx40Warning: env.indexentries() is deprecated. Please use IndexDomain instead.
  t = copy(self.env.indexentries)
c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\rst2pdf\pdfbuilder.py:235: RemovedInSphinx40Warning: env.indexentries() is deprecated. Please use IndexDomain instead.
  docname: self.env.indexentries[docname + '-gen']
c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\rst2pdf\pdfbuilder.py:238: RemovedInSphinx40Warning: env.indexentries() is deprecated. Please use IndexDomain instead.
  self.env.indexentries = {}
c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\rst2pdf\pdfbuilder.py:240: RemovedInSphinx40Warning: env.indexentries() is deprecated. Please use IndexDomain instead.
  self.env.indexentries[dname] = t.get(dname, [])
c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\rst2pdf\pdfbuilder.py:242: RemovedInSphinx40Warning: env.indexentries() is deprecated. Please use IndexDomain instead.
  self.env.indexentries = t
```
### Versions
- Python 3.8.2 (3.8.5 on WSL ubuntu)
- rst2pdf 0.98
- reportlab 3.5.59
- Sphinx 3.0.3 (3.4.3 on WSL ubuntu)

this warning output is consistent using Windows 10 and WSL ubuntu (with version listed above)

### LINKED ISSUE #984: Sphinx version is outdated, update it and fix side-effects
**Description of problem**

We are pinned to Sphinx 1.8.5 at the moment, which is quite outdated but there are breaking changes from where we are to the newest release. However we always want to keep up with releases so this issue is here to co-ordinate our efforts to update, understand the side effects, update the tests, etc.

This originates from #969 where we updated other libraries but this one caused a problem.

### LINKED ISSUE #1014: AttributeError: 'BuildEnvironment' object has no attribute 'indexentries'
build with sphinx version > 4.0.0 fails

[ERROR] pdfbuilder.py:159 Failed to build doc
Traceback (most recent call last):
  File "wpy64-3902\python-3.9.0.amd64\lib\site-packages\rst2pdf\pdfbuilder.py", line 145, in write
    doctree = self.assemble_doctree(
  File "wpy64-3902\python-3.9.0.amd64\lib\site-packages\rst2pdf\pdfbuilder.py", line 232, in assemble_doctree
    t = copy(self.env.**indexentries**)
AttributeError: 'BuildEnvironment' object has no attribute 'indexentries'
FAILED

older version of sphinx throw warning about that: e.g.: sphinx version 3.5.1:
wpy64-3902\python-3.9.0.amd64\lib\site-packages\rst2pdf\pdfbuilder.py:232: RemovedInSphinx40Warning: env.indexentries() is deprecated. Please use IndexDomain instead.
  t = copy(self.env.indexentries)

version: rst2pdf==0.98

pip install sphinx rst2pdf
build pdf docs

### PR DESCRIPTION
**Pull request by akrabat**
*This PR is built on #1021*

Update pdfbuilder.py to work with Sphinx 4.

This required a number of changes:

- Use `self.sphinx_logger.warning()` rather than `self.warn()`.
- Update the way index creation happens as it changed in Sphinx 2.4.0.
- Fix usage of suffix argument in doc2path (Cherry picked from @idryzhov in https://github.com/rst2pdf/rst2pdf/pull/1018).
- Handle the pygments styles that Sphinx 4 now uses and also suppress irrelevant warnings.
- Update the style for code in Sphinx PDFs - that yellow/green background doesn't look good!
- Update Sphinx reference PDFs after manually checking that the changes are acceptable.

Fixes #1014, fixes #984, fixes #980, fixes #749

### CODE REVIEW

**Comment by akrabat** [comment]
This took quite a bit of time to work out what was going on, particularly with the change in the document structure due to the pygments integration.

I was surprised by how few Sphinx tests failed once I got it working though 🙂

**Comment by akrabat** [comment]
Rebased on top of #1021.

**Comment by akrabat** [comment]
@nfraprado would appreciate your review if you have time/are around.

**Review by nfraprado — COMMENTED** [review]
The commit message mentions updating ReportLab but it was actually already updated in https://github.com/rst2pdf/rst2pdf/commit/644a407bd2dad876a1f9eaf87f869e1e0d8d5e3e.

**Comment by akrabat** [comment]
Rebased to pick up changes in #1021 .
